background            #1a1b26
foreground            #d0d0d0
cursor                #38d8a3
cursor_text_color     #11101e
selection_background  #38d8a3
selection_foreground  #11101e

# Black
color0                #2a2a2a
color8                #686868

# Red
color1                #c4676c
color9                #e06c75

# Green
color2                #7ebe8a
color10               #98c379

# Yellow
color3                #d4a957
color11               #e5c07b

# Blue
color4                #7cafc2
color12               #82aaff

# Magenta
color5                #b48ead
color13               #c792ea

# Cyan
color6                #89b8b0
color14               #9cc4bc

# White
color7                #d0d0d0
color15               #f0f0f0

active_tab_foreground   #1a182b
active_tab_background   #38d8a3
inactive_tab_foreground #7b8fbc
inactive_tab_background #2b2940
