#!/bin/sh
INTERNAL=eDP
EXTERNAL=$(xrandr | grep " connected" | grep -v "$INTERNAL" | awk '{print $1}' | head -1)
[ -n "$EXTERNAL" ] && xrandr --output "$EXTERNAL" --above $INTERNAL --auto --output $INTERNAL --auto